package org.cytoscape.UFO.internal;

import java.io.File;
import java.util.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.cytoscape.UFO.Base.Species;

/**
 *
 * @author SUPB
 */
public class ExtractAnnotationDialog extends javax.swing.JDialog {

    public ExtractAnnotationDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        if(MainData.Species==null || MainData.Species.size()==0){
            System.out.println("Loading Species Data...!");
            MainData.Species = new Resource().readSpeciesList("/Species.txt");
        }
        
        this.cboSpecies.removeAllItems();
        Iterator<Species> it_scn = MainData.Species.values().iterator();
        while(it_scn.hasNext()){
            Species sp = it_scn.next();
            String cm = (sp.CommonName.compareTo("")!=0)?" (" + sp.CommonName + ")":"";
            this.cboSpecies.addItem(sp.ScientificName + cm + " - " + sp.Tax_id);
        }
        this.cboSpecies.setSelectedItem("Homo sapiens (human) - 9606");
        this.cboAnnotationType.setSelectedIndex(0);
    }

    public ExtractAnnotationDialog() {
        super();
        initComponents();
//        this.setBounds(0, 0, 548, 213);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgInteraction = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnExtractAnnotationData = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cboAnnotationType = new javax.swing.JComboBox();
        lblSubOntology = new javax.swing.JLabel();
        cboSubOntology = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        txtAnnotationFile = new javax.swing.JTextField();
        btnAnnotationFile = new javax.swing.JButton();
        lblSpecies = new javax.swing.JLabel();
        cboSpecies = new javax.swing.JComboBox();
        lblExtractedAnnotationFile = new javax.swing.JLabel();
        cboDiseaseSource = new javax.swing.JComboBox();
        lblDiseaseSource = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Extract Annotation Data");
        setModal(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        btnExtractAnnotationData.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnExtractAnnotationData.setText("Extract Annotation Data");
        btnExtractAnnotationData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtractAnnotationDataActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Annotation Data"));

        jLabel8.setText("Annotation Data");

        cboAnnotationType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gene Ontology (GO) To Gene", "Human Phenotype Ontology (HPO) To Phenotype", "Disease Ontology (DO) To Gene" }));
        cboAnnotationType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAnnotationTypeActionPerformed(evt);
            }
        });

        lblSubOntology.setText("Sub-Ontology");

        cboSubOntology.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Biological Process", "Cellular Component", "Molecular Function" }));
        cboSubOntology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSubOntologyActionPerformed(evt);
            }
        });

        jLabel11.setText("Annotation File");

        btnAnnotationFile.setText("...");
        btnAnnotationFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnotationFileActionPerformed(evt);
            }
        });

        lblSpecies.setText("Species");

        cboSpecies.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Homo sapiens (9606)", "Arabidopsis thaliana (3702)", "Bos taurus (9913)", "Caenorhabditis elegans (6239)", "Gallus gallus (9031)", "Rattus norvegicus (10116)" }));

        lblExtractedAnnotationFile.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        lblExtractedAnnotationFile.setText("Extracted File");
        lblExtractedAnnotationFile.setAutoscrolls(true);

        cboDiseaseSource.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OMIM", "DECIPHER" }));

        lblDiseaseSource.setText("Disease Source");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(lblExtractedAnnotationFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(lblSubOntology)
                            .addComponent(jLabel11)
                            .addComponent(lblSpecies)
                            .addComponent(lblDiseaseSource))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(txtAnnotationFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAnnotationFile, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cboAnnotationType, 0, 397, Short.MAX_VALUE)
                            .addComponent(cboDiseaseSource, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboSubOntology, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboSpecies, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cboAnnotationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnnotationFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnnotationFile)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboDiseaseSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiseaseSource))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubOntology)
                    .addComponent(cboSubOntology, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboSpecies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSpecies))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblExtractedAnnotationFile, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExtractAnnotationData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExtractAnnotationData, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExtractAnnotationDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtractAnnotationDataActionPerformed
        
        String OutputFile = "";
        String AnnotationFile = txtAnnotationFile.getText();
        
        if(cboAnnotationType.getSelectedIndex()==0){
            String SubOntology="";
            if(cboSubOntology.getSelectedIndex()==0){
                SubOntology = "BP";
            }else if(cboSubOntology.getSelectedIndex()==1){
                SubOntology = "CC";
            }else{
                SubOntology = "MF";
            }
            String Species = cboSpecies.getSelectedItem().toString();
            int SpeciesID = Integer.parseInt(Species.substring(Species.indexOf("-") + 2, Species.length()));
            
            OutputFile = "Data\\Annotation_Gene2GO_" + SpeciesID + "_" + SubOntology + ".txt";
            lblExtractedAnnotationFile.setText(new File(OutputFile).getAbsolutePath());
            
            Common.ExtractGene2GORelation(SubOntology, SpeciesID, AnnotationFile, OutputFile);
            
        }else if(cboAnnotationType.getSelectedIndex()==1){
            String DiseaseSource = "";
            DiseaseSource = cboDiseaseSource.getSelectedItem().toString();
            OutputFile = "Data\\Annotation_OMIM2HPO_" + DiseaseSource + ".txt";
            lblExtractedAnnotationFile.setText(new File(OutputFile).getAbsolutePath());
            
            Common.ExtractOMIM2HPORelation(DiseaseSource, AnnotationFile, OutputFile);
        }else{
            OutputFile = "Data\\Annotation_Gene2DO.txt";
            lblExtractedAnnotationFile.setText(new File(OutputFile).getAbsolutePath());
            
            Common.ExtractGene2DORelation(AnnotationFile, OutputFile);
        }
        JOptionPane.showMessageDialog(this.getRootPane(), "Done!");
        
    }//GEN-LAST:event_btnExtractAnnotationDataActionPerformed

    private void cboSubOntologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSubOntologyActionPerformed

    }//GEN-LAST:event_cboSubOntologyActionPerformed

    private void cboAnnotationTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAnnotationTypeActionPerformed
        // TODO add your handling code here:
        if(this.cboAnnotationType.getSelectedIndex()==0){//GO
            this.cboSubOntology.setVisible(true);
            this.lblSubOntology.setVisible(true);
            
            this.cboDiseaseSource.setVisible(false);
            this.lblDiseaseSource.setVisible(false);
            
            this.cboSpecies.setVisible(true);
            this.lblSpecies.setVisible(true);
            
            txtAnnotationFile.setText("Data\\gene2go");

        }else if(this.cboAnnotationType.getSelectedIndex()==1){//HPO
            this.cboSubOntology.setVisible(false);
            this.lblSubOntology.setVisible(false);
            
            this.cboDiseaseSource.setVisible(true);
            this.lblDiseaseSource.setVisible(true);
            
            this.cboSpecies.setVisible(false);
            this.lblSpecies.setVisible(false);
            
            txtAnnotationFile.setText("Data\\phenotype_annotation_hpoteam.tab");

        }else if(this.cboAnnotationType.getSelectedIndex()==2){//DO
            this.cboSubOntology.setVisible(false);
            this.lblSubOntology.setVisible(false);
            
            this.cboDiseaseSource.setVisible(false);
            this.lblDiseaseSource.setVisible(false);
            
            this.cboSpecies.setVisible(false);
            this.lblSpecies.setVisible(false);
            
            txtAnnotationFile.setText("Data\\DBAR_Ver.txt");
        }

    }//GEN-LAST:event_cboAnnotationTypeActionPerformed

    private void btnAnnotationFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnotationFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        //fc.setFileFilter(new FileTypeFilter());
        fc.setDialogTitle("Select Annotation file");
        fc.setCurrentDirectory(new File("."));

        int returnVal=fc.showOpenDialog(this.getRootPane());
        //int returnVal=fc.showSaveDialog(this);
        String fileName="";
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            fileName=fc.getSelectedFile().getAbsolutePath();
            txtAnnotationFile.setText(fileName);
        }else{
            return;
        }
    }//GEN-LAST:event_btnAnnotationFileActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgInteraction;
    private javax.swing.JButton btnAnnotationFile;
    public static javax.swing.JButton btnExtractAnnotationData;
    private javax.swing.JComboBox cboAnnotationType;
    private javax.swing.JComboBox cboDiseaseSource;
    private javax.swing.JComboBox cboSpecies;
    private javax.swing.JComboBox cboSubOntology;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDiseaseSource;
    private javax.swing.JLabel lblExtractedAnnotationFile;
    private javax.swing.JLabel lblSpecies;
    private javax.swing.JLabel lblSubOntology;
    private javax.swing.JTextField txtAnnotationFile;
    // End of variables declaration//GEN-END:variables

}
